name: teste_unitario_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  path: ^1.8.0
  test: ^1.22.2

dev_dependencies:
  lints: ^2.0.0
